### ISSUE TITLE
`404 The 'redirect_uri' parameter must be an absolute URI that is whitelisted in the client app settings `

### ISSUE THREAD

**Issue by sonu3706** [okta/okta-spring-boot#105]
@bdemers  As you have closed the same issue earlier which I am unable to open hence creating new issue for the same.
In my scenario, I have added  `http://localhost:8080/login` as a redirect URI in okta console and when I hit `http://localhost:8080/secondhome` from the browser I get okta login page and then I give my credentials after that I get `Too many redirect` issue.
And If I remove `http://localhost:8080/login` from Okta console I get `404 The 'redirect_uri' parameter must be an absolute URI that is whitelisted in the client app settings ` issue

**Comment by bdemers** [comment]
@sonu3706 which version are you using?

**Comment by sonu3706** [comment]
Spring boot version-- 2.1.1

**Comment by bdemers** [comment]
What does your config look like on the Okta side and your application.properties/yml?

**Comment by sonu3706** [comment]
okta.oauth2.issuer=https://dev-376319.oktapreview.com/oauth2/default
okta.oauth2.clientId=
okta.oauth2.clientSecret=
okta.oauth2.discovery-uri=https://dev-376319.oktapreview.com/.well-known/openid-configuration
okta.client.token=
security.oauth2.client.accessTokenUri=https://dev-376319.oktapreview.com/oauth2/default/v1/token
security.oauth2.client.userAuthorizationUri=https://dev-376319.oktapreview.com/oauth2/default/v1/authorize
security.oauth2.resource.userInfoUri=https://dev-376319.oktapreview.com/oauth2/default/v1/userinfo
security.oauth2.resource.jwk.keySetUri=https://dev-376319.oktapreview.com/oauth2/default/v1/keys
security.oauth2.resource.tokenInfoUri=https://dev-376319.oktapreview.com/oauth2/default/v1/token
#security.oauth2.sso.loginPath=/login
security.oauth2.client.client-id=
security.oauth2.client.client-secret=RvBLnmAY_dAyV2_WVpuNrf8SpwEV4mFqCNFir6_V

**Comment by bdemers** [comment]
You should set either the `okta.oauth2.*` props or the Spring ones (not both).

just the okta ones should be all you need:
```
okta.oauth2.issuer=https://dev-376319.oktapreview.com/oauth2/default
okta.oauth2.clientId=<something>
okta.oauth2.clientSecret=<something-else>
```

All the other properties can be resolved from the issuer.

You may also want to reset your secret ;)

Spring's default redirect uri would be `<your-application-url>/login/oauth2/code/okta` (assuming you are using the latest Spring and Okta starter versions).  Otherwise what happens is Spring redirects you to Okta, you login to Okta successfully, get redirected back to `/wrong-page`. You are not authorized to access `/wrong-page`, so Spring redirects back to Okta.  You are already logged into Okta, so you are redirected back to `/wrong-page` (and the cycle continues).

Give that a shot, and if that isn't what you are seeing grab the browser network calls (preserve log) and add it here.

Keep us posted!

**Comment by bdemers** [comment]
@sonu3706 closing, but leave us a note here if you are still running into problems!
