### ISSUE TITLE
Add support to inject the java okta-sdk

### ISSUE THREAD

**Issue by bdemers** [okta/okta-spring-boot#15]

**Comment by Prophet32j** [comment]
If I follow the README for the SDK, will it conflict with the starter at all?

**Comment by bdemers** [comment]
Nope, you should be all set.  If you want to take an early look at adding support for the SDK in this project take a look at #16

**Comment by Prophet32j** [comment]
I already did it last night. It was very simple to do.

With this PR, are you combining in a single yaml file, application.yml, or are you still trying to configure a separate yaml for okta? I combined all of mine into my application.yml since it makes it much simpler to manage, and I already had okta properties for this project.

```java
@Configuration
public class OktaConfig {
	
  @Value("${okta.client.token}")
	private String oktaApiToken;
	
	@Value("${okta.client.orgUrl}")
	private String oktaOrgUrl;
	
	@Bean
	public Client oktaClient() {
		ClientCredentials clientCredentials = new TokenClientCredentials(oktaApiToken);
		return Clients
                      .builder()
                      .setOrgUrl(oktaOrgUrl)
                      .setClientCredentials(clientCredentials)
                      .build();
	}
	
}

```

**Comment by bdemers** [comment]
The goal is to allow for the ability to use both files, where the application.yml would take priority over it.

The result is basically the same as your example, the `Client` object is available for injection.

Keep us posted!
