### ISSUE TITLE
Validate Client ID for Angular UI to Spring boot resource server

### ISSUE THREAD

**Issue by konda007** [okta/okta-spring-boot#168]
Hi,

I have a scenario to Validate Client ID for Angular UI to Spring boot resource server. The token would be generated from UI and passing to API request, here the JWT token being validated against Issuer and Audience, but not client id. So the request may be successful for any valid JWT token. I want to enforce to validate client id as well.
 I have added client id in application.properties, but the JWT token is not getting validated by checking client id present in properties with JWT token.

Can you help me how to get this scenario worked out.

**Comment by bdemers** [comment]
Sorry for the late reply @konda007.
JWT access token validation is vendor-specific, Okta recommends validating the issuer and audience claims. In this case your "audience" value should be unique to your application.

That said, since it's just a JWT, you can validate additional claims, just provide a `JwtDecoder` Bean, similar to:

https://github.com/okta/okta-spring-boot/blob/0fab5771d56b4f653ee4ae980a1dfa63cd58bbf3/oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java#L45-L51
